#!/usr/bin/env bash

case $BLOCK_BUTTON in
  1) ~/settings/i3/scripts/xkblayout-state set +1 ;; # left click to change language 
esac


LNG=$(~/settings/i3/scripts/xkblayout-state print %s | awk '{print toupper($0)}')

case $LNG in
  "US")
    CLR=\#00FF00 ;; # green
  "RU")
    CLR=\#FF0000 ;; # red
  *)
    CLR=\#FFFFFF ;; # all others default-white
esac

echo "$LNG"
echo "$LNG"
echo "$CLR"
